# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
minimum_pre_commit_version: 2.8.0
default_stages: [commit, push, manual]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: check-executables-have-shebangs
  - id: check-ast
  - id: check-added-large-files
    args: [--maxkb=800]
  - id: debug-statements
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: fix-encoding-pragma
  - id: requirements-txt-fixer
  # - id: no-commit-to-branch
  #   args: [--branch, master]

# - repo: https://github.com/pre-commit/mirrors-autopep8
#   rev: v1.5.1
#   hooks:
#   - id: autopep8

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
  - id: git-check

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.13
  hooks:
  - id: remove-crlf

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: [--max-line-length=120]

- repo: https://gitlab.com/devopshq/gitlab-ci-linter
  rev: v1.0.3
  hooks:
  - id: gitlab-ci-linter

- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.2.0
  hooks:
  - id: detect-secrets
    args: ["--disable-plugin", "Base64HighEntropyString", "--disable-plugin", "KeywordDetector", "--exclude-files", "README.md"]

