repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: eks
  url: https://aws.github.io/eks-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: grafana
  url: https://grafana.github.io/helm-charts

# helmBinary: path/to/helm3

helmDefaults:
  wait: true

releases:
  - name: chart-1
    namespace: app1-ns
    createNamespace: true
    chart: argo/argo-cd
    version: 3.26.8
    values:
      - ./chart-1/values.env2.yaml
#   secrets:
#     - ./chart-1/secrets.env2.yaml
