metrics-server:
  resources:
    requests:
      cpu: 250m
      memory: 250Mi

  extraArgs: [ "--kubelet-preferred-address-types=InternalIP", "--kubelet-insecure-tls=true" ]

  apiService:
    create: true

  rbac:
    create: true
