applications:
- applicationName: dev-app-of-apps
  applicationSpecs: |
    project: dev-tooling

    source:
      repoURL: https://git.example.com/helm-charts-xxx
      targetRevision: master
      path: argo-application
      helm:
        releaseName: dev-apps
        valueFiles:
        - ./values.dev.yaml

    destination:
      server: https://kubernetes.default.svc
      namespace: argocd

    syncPolicy: {}

    ignoreDifferences:
    - group: 'argoproj.io'
      kind: Application
      jsonPointers:
      - /spec/source/helm
