applications:

# Tooling

- applicationName: dev-metrics-server
  applicationSpecs: |
    project: dev-tooling
    source:
      repoURL: https://git.example.com/helm-charts-xxx
      targetRevision: master
      path: metrics-server
      helm:
        releaseName: metrics-server
        valueFiles:
        - ./values.dev.yaml
    destination:
      server: https://kube-api-server.example.com
      namespace: tooling
    syncPolicy: {}
