DOTFILES_DIR=/dotfiles/zsh

source $DOTFILES_DIR/antigen.zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle supercrabtree/k
antigen bundle eendroroy/zed-zsh
antigen bundle zsh-users/zsh-autosuggestions

antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen apply

git config --global user.email "jjaniec@student.42.fr"
git config --global user.name "Joffrey Janiec"
