export DOTFILES_DIR=/dotfiles

#### Antigen plugins ####

source $DOTFILES_DIR/zsh/antigen.zsh

antigen bundle zdharma/fast-syntax-highlighting
antigen bundle supercrabtree/k
antigen bundle eendroroy/zed-zsh
antigen bundle zsh-users/zsh-autosuggestions

antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

#antigen bundle sobolevn/wakatime-zsh-plugin

antigen apply

#### Git config ####

git config --global user.email "jjaniec@student.42.fr"
git config --global user.name "Joffrey Janiec"

if [ "$(uname -s)" = "Linux" ];
then
	git config --global credential.helper cache;
else
	git config --global credential.helper osxkeychain;
fi;


#### Aliases and exports ####

#export WAKATIME_HOME=$DOTFILES_DIR/zsh/.wakatime.cfg

#alias ls='k'

#### Scripts ####
