#### Setup

ANTIGEN_DIR=/zsh/antigen

setopt autocd							# If only a directory is entered, cd there

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'	# Case insensitive auto-completion

# Load dotfiles location

if [ -z "$DOTFILES_DIR" ];
then
	stat /dotfiles > /dev/null 2>&1;
	if [ $? -ne 0 ];
	then
		export DOTFILES_DIR=~/dotfiles;
	else
		export DOTFILES_DIR=/dotfiles;
	fi;
fi;

# Auto-update dotfiles if new commits found

if [ -n "$DOTFILES_DIR" ];
then
	DOTFILES_BRANCH=$(git -C $DOTFILES_DIR name-rev --name-only HEAD)

	git -C $DOTFILES_DIR fetch origin $DOTFILES_BRANCH > /dev/null 2>&1
	git -C $DOTFILES_DIR diff --exit-code master...origin/$DOTFILES_BRANCH > /dev/null 2>&1
	if [ $? != 0 ];
	then
		echo "\e[32mRemote has new commits ! Updating ...\e[39m"
		git -C $DOTFILES_DIR merge origin/$DOTFILES_BRANCH
	fi;
fi;

#### Antigen plugins ####

if [ -n "$DOTFILES_DIR" ];
then
	if ! [ -f $DOTFILES_DIR/zsh/antigen/antigen.zsh ];
	then
		git clone https://github.com/zsh-users/antigen $DOTFILES_DIR$ANTIGEN_DIR
		git -C $DOTFILES_DIR$ANTIGEN_DIR checkout develop
	fi;
	git -C $DOTFILES_DIR$ANTIGEN_DIR fetch origin develop 2> /dev/null
	git -C $DOTFILES_DIR$ANTIGEN_DIR diff --exit-code origin/develop
	if [ $? != 0 ];
	then
		echo "\e[32mUpdating antigen...\e[39m"
		git -C $DOTFILES_DIR$ANTIGEN_DIR merge origin/develop
	fi;

	source $DOTFILES_DIR$ANTIGEN_DIR/antigen.zsh

	# Pure theme
	antigen bundle mafredri/zsh-async
	antigen bundle sindresorhus/pure

	# Additional features
	antigen bundle zsh-users/zsh-autosuggestions
	antigen bundle zsh-users/zsh-completions
	antigen bundle zdharma/fast-syntax-highlighting

	#antigen bundle sobolevn/wakatime-zsh-plugin

	# Additional commands
	antigen bundle eendroroy/zed-zsh

	antigen apply
fi;

#### Git config ####

git config --global user.email "jjaniec@student.42.fr"
git config --global user.name "Joffrey Janiec"

if [ "$(uname -s)" = "Linux" ];
then
	git config --global credential.helper cache;
else
	git config --global credential.helper osxkeychain;
fi;

#### Aliases and exports ####

#export WAKATIME_HOME=$DOTFILES_DIR/zsh/.wakatime.cfg

alias glog="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)'"
alias psc="ps xawf -eo pid,user,cgroup,args"

# Enable coloration in less
export LESS_TERMCAP_mb=$'\E[01;32m'
export LESS_TERMCAP_md=$'\E[01;32m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;47;34m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;36m'
export LESS=-r

#### Scripts ####

# Source 42 specific dotfiles
if [ $(hostname | grep -E 'e[1-9]{1,2}r[1-9]{1,2}p[1-9]{1,2}.42.fr') ];
then
	source ~/42_dotfiles/.zshrc
	source ~/.brewconfig
fi;
